services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: always

  app:
    build: .
    container_name: express-app
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    networks:
      - backend
    command: ['pm2', 'start', 'dist/bin/www.js', '--no-daemon']
    restart: always

volumes:
  mongo_data:
    driver: local

networks:
  backend:
    driver: bridge
